if(EXISTS "/home/hadi.sharifi/ws/faiss/faiss/gpu/test/TestGpuIndexIVFScalarQuantizer[1]_tests.cmake")
  include("/home/hadi.sharifi/ws/faiss/faiss/gpu/test/TestGpuIndexIVFScalarQuantizer[1]_tests.cmake")
else()
  add_test(TestGpuIndexIVFScalarQuantizer_NOT_BUILT TestGpuIndexIVFScalarQuantizer_NOT_BUILT)
endif()
