if(EXISTS "/home/hadi.sharifi/ws/faiss/faiss/gpu/test/TestGpuIndexIVFFlat[1]_tests.cmake")
  include("/home/hadi.sharifi/ws/faiss/faiss/gpu/test/TestGpuIndexIVFFlat[1]_tests.cmake")
else()
  add_test(TestGpuIndexIVFFlat_NOT_BUILT TestGpuIndexIVFFlat_NOT_BUILT)
endif()
